import carousel1 from "./images/carousel1.jpg";
import carousel2 from "./images/carousel2.jpg";
import carousel3 from "./images/carousel3.jpg";
import carousel4 from "./images/carousel4.jpg";
import g1 from "./images/g1.jpg";
import g2 from "./images/g2.jpg";
import g3 from "./images/g3.jpg";
import g4 from "./images/g4.jpg";
import g5 from "./images/g5.jpg";
import g6 from "./images/g6.jpg";
import g7 from "./images/g7.jpg";
import g8 from "./images/g8.jpg";
import p1 from "./images/p1.jpg";
import p2 from "./images/p2.jpg";
import p3 from "./images/p3.jpg";
import p4 from "./images/p4.jpg";
import abtbanner from "./images/abtbanner.jpg";
import part1 from "./images/part1.jpg";
import part2 from "./images/part2.jpg";
import part3 from "./images/part3.jpg";
import part4 from "./images/part4.jpg";
import dialogs1 from "./images/dialog1.jpg";
import dialogs2 from "./images/dialog2.jpg";
import dialogs3 from "./images/dialog3.jpg";

export const CARO1 = carousel1;
export const CARO2 = carousel2;
export const CARO3 = carousel3;
export const CARO4 = carousel4;
export const G1 = g1;
export const G2 = g2;
export const G3 = g3;
export const G4 = g4;
export const G5 = g5;
export const G6 = g6;
export const G7 = g7;
export const G8 = g8;
export const P1 = p1;
export const P2 = p2;
export const P3 = p3;
export const P4 = p4;
export const ABTBANNER = abtbanner;
export const PART1 = part1;
export const PART2 = part2;
export const PART3 = part3;
export const PART4 = part4;
export const DIA1 = dialogs1;
export const DIA2 = dialogs2;
export const DIA3 = dialogs3;
